jobs:
 - name: cg_sales_orders_fact_night_run
   targetName: cg-gbq-p 
   schedule: "45 6 * * *"
   timeout: 2h30m
   steps:
     - name: run models 
       command: dbt run --models @consumption_zone 
 - name: cg_sales_orders_fact_morning_run
   schedule: "45 18 * * *" 
   timeout: 2h30m
   steps:
     - name: run models
       command: dbt run --models @consumption_zone

 -  name: cg_sales_orders_fact_onetime_run
    targetName: cg-gbq-p 
    schedule: "00 12 * * *"
    timeout: 2h30m
    steps:
     - name: run models 
       command: dbt run --models @consumption_zone 