jobs:
 - name: staging_zone_dbt_first_12hrun
   targetName: cg-gbq-p 
   schedule: "30 6 * * *"
   timeout: 2h30m
   steps:
     - name: run models 
       command: dbt run --models @consumption_zone 
 - name: staging_zone_dbt_second_12hrun
   schedule: "30 18 * * *" 
   timeout: 2h30m
   steps:
     - name: run models
       command: dbt run --models @consumption_zone