jobs:
 - name: daily
   targetName: cg-gbq-p 
   schedule: 0 */12 * * * 
   timeout: 2h30m
   steps:
     - name: run models 
       command: dbt run --models staging_zone 
 - name: nightly
   schedule: 0 */12 * * * 
   steps:
     - name: run models
       command: dbt run --models staging_zone