{{
    config(
        materialized = 'table',
		tags = 'invoice_payment_schedule'	
    )
}}

with invoice_payment_schedule_col as (
select 
  ar_payment_schedule_payment_schedule_id  ,
  _fivetran_synced  ,
  ar_payment_schedule_acctd_amount_due_remaining  ,
  ar_payment_schedule_active_claim_flag  ,
  ar_payment_schedule_actual_date_closed  ,
  ar_payment_schedule_amount_adjusted  ,
  ar_payment_schedule_amount_adjusted_pending  ,
  ar_payment_schedule_amount_applied  ,
  ar_payment_schedule_amount_credited  ,
  ar_payment_schedule_amount_due_original  ,
  ar_payment_schedule_amount_due_remaining  ,
  ar_payment_schedule_amount_in_dispute  ,
  ar_payment_schedule_amount_line_items_original  ,
  ar_payment_schedule_amount_line_items_remaining  ,
  ar_payment_schedule_amount_on_account  ,
  ar_payment_schedule_amount_other_account  ,
  ar_payment_schedule_associated_cash_receipt_id  ,
  ar_payment_schedule_br_amount_assigned  ,
  ar_payment_schedule_call_date_last  ,
  ar_payment_schedule_cash_receipt_id  ,
  ar_payment_schedule_collector_last  ,
  ar_payment_schedule_cons_inv_id  ,
  ar_payment_schedule_cons_inv_id_rev  ,
  ar_payment_schedule_created_by  ,
  ar_payment_schedule_creation_date  ,
  ar_payment_schedule_cust_trx_type_seq_id  ,
  ar_payment_schedule_customer_id  ,
  ar_payment_schedule_customer_site_use_id  ,
  ar_payment_schedule_customer_trx_id  ,
  ar_payment_schedule_del_contact_email_address  ,
  ar_payment_schedule_discount_taken_earned  ,
  ar_payment_schedule_discount_taken_unearned  ,
  ar_payment_schedule_dispute_date  ,
  ar_payment_schedule_due_date  ,
  ar_payment_schedule_dunning_level_override_date  ,
  ar_payment_schedule_exchange_date  ,
  ar_payment_schedule_exchange_rate  ,
  ar_payment_schedule_exchange_rate_type  ,
  ar_payment_schedule_exclude_from_cons_bill_flag  ,
  ar_payment_schedule_exclude_from_dunning_flag  ,
  ar_payment_schedule_follow_up_code_last  ,
  ar_payment_schedule_follow_up_date_last  ,
  ar_payment_schedule_freight_original  ,
  ar_payment_schedule_freight_remaining  ,
  ar_payment_schedule_gl_date  ,
  ar_payment_schedule_gl_date_closed  ,
  ar_payment_schedule_in_collection  ,
  ar_payment_schedule_invoice_currency_code  ,
  ar_payment_schedule_last_charge_date  ,
  ar_payment_schedule_last_update_date  ,
  ar_payment_schedule_last_update_login  ,
  ar_payment_schedule_last_updated_by  ,
  ar_payment_schedule_module_id  ,
  ar_payment_schedule_number_of_due_dates  ,
  ar_payment_schedule_object_version_number  ,
  ar_payment_schedule_org_id  ,
  ar_payment_schedule_payment_approval  ,
  ar_payment_schedule_payment_schedule_class_1  ,
  ar_payment_schedule_print_request_id  ,
  ar_payment_schedule_program_application_id  ,
  ar_payment_schedule_program_id  ,
  ar_payment_schedule_program_update_date  ,
  ar_payment_schedule_promise_amount_last  ,
  ar_payment_schedule_promise_date_last  ,
  ar_payment_schedule_receipt_confirmed_flag  ,
  ar_payment_schedule_receivables_charges_charged  ,
  ar_payment_schedule_receivables_charges_remaining  ,
  ar_payment_schedule_request_id  ,
  ar_payment_schedule_reserved_type  ,
  ar_payment_schedule_reserved_value  ,
  ar_payment_schedule_reversed_cash_receipt_id  ,
  ar_payment_schedule_seed_data_source  ,
  ar_payment_schedule_selected_for_receipt_batch_id  ,
  ar_payment_schedule_staged_dunning_level  ,
  ar_payment_schedule_status  ,
  ar_payment_schedule_tax_original  ,
  ar_payment_schedule_tax_remaining  ,
  ar_payment_schedule_term_id  ,
  ar_payment_schedule_terms_sequence_number  ,
  ar_payment_schedule_trx_date  ,
  ar_payment_schedule_trx_number  ,
  _fivetran_deleted,
  current_datetime() as load_datetime
  
  from 
  `cg-gbq-p.oracle_fusion_fscm_finextract_arbiccextract.payment_schedule_extract_pvo`)
  
  select * from invoice_payment_schedule_col