
version: 2

models:
    - name: customer_account_master
    - name: invoice_legal_entity
    - name: invoice_payment_schedule
    - name: invoice_transaction_header
    - name: invoice_transaction_line
    - name: sales_orders_fulfill_line
    - name: sales_orders_header
    - name: sales_orders_inventory_org_parameters_cycle_count
    - name: sales_orders_item_extract
    - name: sales_orders_location
    - name: sales_orders_order_address
    - name: sales_orders_party_site