
version: 2

models:
    - name: cg_dim_customer_class
      #description: "A starter dbt model"
      columns:
          - name: s_key
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: cg_report_pace_sales
      #description: "A starter dbt model"
      columns:
          - name: s_key
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    
    - name: cg_report_pace_sales_view
      #description: "A starter dbt model"
      columns:
          - name: s_key
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
